
TITLE = "Nydd"
SCREEN_W = 128
SCREEN_H = 128
FPS = 60
SECS_PER_FRAME = 1.0/FPS

IMAGE_FILE_TILES = "assets/img00.png"
IMAGE_FILE_SPRITES = "assets/img01.png"
IMAGE_FILE_GUI = "assets/img02.png"
IMAGE_BANK_TILES = 0
IMAGE_BANK_SPRITES = 1
IMAGE_BANK_GUI = 2

TILEMAP_FILE_TILES = "assets/map00_tiles.csv"
TILEMAP_WORLD_TILES = 0
TILEMAP_FILE_SPAWNS = "assets/map00_spawns.csv"
TILEMAP_WORLD_SPAWNS = 1
TILEMAP_TILES_WIDE = 2048 // 8
TILE_IMAGE_TILES_WIDE = 256 // 8
TILEMAP_SCREENS_WIDE = 2048 // SCREEN_W

START_HP = 100
MAX_HP = 100
START_MP = 0
MAX_MP = 100
MAX_GOLD = 99999999

HUD_H = 16
VIEW_H = SCREEN_H - HUD_H
